version: '3.3'
services:
  wine:
    #init: true
    privileged: true
    build: .
    #build:
    #  context: .
    hostname: wine
    volumes:
      - winevol:/home/zandronum/wine/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:rw
      - $XAUTHORITY:$XAUTHORITY
    devices:
      - "/dev/snd"
    #network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY
    image: innovanon/docker-wine:latest
    container_name: docker-wine

volumes:
  winevol:

